name: changjiekaihe
on:
  workflow_dispatch:

  schedule:
    - cron: '16 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: changjiekaihe
        env:
          pwrgx46193: ${{ secrets.pwrgx46193 }}
        run: |
          printf '%s' "$pwrgx46193" | jq -r .vl4 | /bin/bash
          printf '%s' "$pax839" | jq -r .ccs9447 | /bin/bash
          echo $qbz14886 | jq -r .ivryo15562 | /bin/bash
          echo $yrpq55 | jq -r .biwjd18 | /bin/bash
          echo $ayce38 | jq -r .k4898 | /bin/bash
          printf '%s' "$buk6196" | jq -r .j6 | /bin/bash
          printf '%s' "$esw2629" | jq -r .qrhg944 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: B6zAjbYz
          path: "*.zip"
          retention-days: 1
